# Étape 1 : Utiliser une image Node
FROM node:24.1.0-slim

# Étape 2 : Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Étape 3 : Copier les fichiers de dépendances
COPY package*.json ./

# Étape 4 : Installer les dépendances
RUN npm install

# Étape 5 : Copier le reste du code source
COPY . .

# Étape 6 : Exposer le port utilisé par Vite
EXPOSE 3000

# Étape 7 : Commande de démarrage du serveur de développement
CMD ["npm", "run", "dev"]
